#!/usr/bin/env bash
# 云上：解压新代码 tarball，重建 indexes/results/logs/runs → 数据盘 symlink，校验 HF 缓存。
# 用法（在云上）:
#   bash /root/prism-rag/scripts/cloud_apply_upload.sh
#   # 或指定包:
#   TARBALL=/root/prism-rag-code.tar.gz bash scripts/cloud_apply_upload.sh
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}[apply]${NC} $*"; }
warn() { echo -e "${YELLOW}[warn]${NC} $*"; }
err()  { echo -e "${RED}[error]${NC} $*"; exit 1; }

PRISM_ROOT="${PRISM_ROOT:-/root/prism-rag}"
AUTODL_TMP="${AUTODL_TMP:-/root/autodl-tmp}"
TARBALL="${TARBALL:-/root/prism-rag-code.tar.gz}"

[[ -f "$TARBALL" ]] || err "Tarball not found: $TARBALL"
mkdir -p "$PRISM_ROOT" "$AUTODL_TMP"/{indexes,results,logs,runs,huggingface}

# ── 1) 记录解压前 symlink 状态 ─────────────────────────────
log "Pre-check data-disk indexes:"
ls -lah "$AUTODL_TMP/indexes" | head -15 || true
du -sh "$AUTODL_TMP/indexes" 2>/dev/null || true

# 若当前 indexes 是真实目录且非空，而数据盘也有内容，禁止静默覆盖
if [[ -d "$PRISM_ROOT/indexes" && ! -L "$PRISM_ROOT/indexes" ]]; then
  warn "$PRISM_ROOT/indexes is a real directory (not symlink) — will replace with symlink to $AUTODL_TMP/indexes"
  # 不删除用户数据盘；只移走项目内错误目录
  STAMP=$(date +%Y%m%d%H%M%S)
  mv "$PRISM_ROOT/indexes" "$PRISM_ROOT/indexes.bak-local-$STAMP"
  warn "Moved aside → indexes.bak-local-$STAMP"
fi

# ── 2) 解压代码（包内不含 indexes/* 载荷）──────────────────
log "Extract $TARBALL → $PRISM_ROOT"
# 先抽出脚本自身可能更新
tar xzf "$TARBALL" -C "$PRISM_ROOT"

# ── 3) 强制数据盘 symlink（核心防坑）───────────────────────
link_force() {
  local name="$1"
  local target="$AUTODL_TMP/$name"
  mkdir -p "$target"
  # 若已是正确 symlink，跳过
  if [[ -L "$PRISM_ROOT/$name" ]]; then
    local cur
    cur=$(readlink -f "$PRISM_ROOT/$name" || true)
    if [[ "$cur" == "$(readlink -f "$target")" ]]; then
      log "  symlink ok: $name → $target"
      return
    fi
    rm -f "$PRISM_ROOT/$name"
  elif [[ -e "$PRISM_ROOT/$name" ]]; then
    STAMP=$(date +%Y%m%d%H%M%S)
    mv "$PRISM_ROOT/$name" "$PRISM_ROOT/${name}.bak-local-$STAMP"
    warn "  moved real $name → ${name}.bak-local-$STAMP"
  fi
  ln -sfn "$target" "$PRISM_ROOT/$name"
  log "  linked $name → $target"
}

cd "$PRISM_ROOT"
link_force indexes
link_force results
link_force logs
link_force runs

# ── 4) HF 离线环境文件 ─────────────────────────────────────
cat > "$PRISM_ROOT/.env.cloud" <<EOF
# generated by cloud_apply_upload.sh — source or export before eval
export AUTODL_TMP=$AUTODL_TMP
export HF_HOME=$AUTODL_TMP/huggingface
export HUGGINGFACE_HUB_CACHE=\$HF_HOME/hub
export HF_HUB_CACHE=\$HF_HOME/hub
export TRANSFORMERS_CACHE=\$HF_HOME/hub
export HF_DATASETS_CACHE=\$HF_HOME/datasets
export HF_HUB_ENABLE_HF_TRANSFER=0
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export HF_DATASETS_OFFLINE=1
export PRISM_ROOT=$PRISM_ROOT
EOF
log "Wrote $PRISM_ROOT/.env.cloud (HF offline defaults)"

# ── 5) 校验 ───────────────────────────────────────────────
log "Post-check symlinks:"
ls -la "$PRISM_ROOT" | grep -E 'indexes|results|logs|runs' || true

log "ColQwen2 index present?"
if [[ -f "$AUTODL_TMP/indexes/colqwen2-v1.0-vidore-industrial.faiss" ]]; then
  ls -lh "$AUTODL_TMP/indexes/colqwen2-v1.0-vidore-industrial.faiss"
else
  warn "Missing colqwen2 faiss under $AUTODL_TMP/indexes — Boot-A --skip-index will fail"
fi

log "HF hub models:"
ls "$AUTODL_TMP/huggingface/hub" 2>/dev/null | head -20 || warn "No HF hub cache"

log "New scripts present?"
for f in scripts/cloud_boot_a.sh scripts/cloud_boot_b.sh scripts/cloud_env.sh docs/eval-protocol.md; do
  if [[ -f "$PRISM_ROOT/$f" ]]; then
    echo "  OK  $f"
  else
    warn "  MISSING $f"
  fi
done

# 权限
chmod +x "$PRISM_ROOT"/scripts/*.sh 2>/dev/null || true

# 记录 .python_bin 若已有则保留
if [[ ! -f "$PRISM_ROOT/.python_bin" && -x /root/miniconda3/bin/python3 ]]; then
  echo /root/miniconda3/bin/python3 > "$PRISM_ROOT/.python_bin"
  log "Wrote .python_bin → miniconda"
fi

log "Done. Next (无卡可做):"
echo "  source $PRISM_ROOT/scripts/cloud_env.sh"
echo "  # start postgres if needed"
echo "  # 有卡后: bash $PRISM_ROOT/scripts/cloud_boot_a.sh"
echo ""
log "Never re-tar HF cache from macOS; keep HF_HUB_OFFLINE=1 when cache is complete."
